# -*- coding: utf-8 -*-
"""
Main program for creating IEC 61850 MMS server using the libIEC61850 server stack.

A magic tool to build and run virtual IEC 61850 server by using an IEC 61850 compliant SCL
data model.

@author: Shuo Chen

TODO: reformulate the notes and hints into a solid documentation
TODO: resolve the issue of jumping between parent and current working directory when the implementation is completely
    done, refer to the answer in this post:
    https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder/50194143#50194143
Note:
    - data model validation is not a part of this module, assuming the SCL file has no topological error and all data
        objects, attributes are assigned the correct type/class
    - this module works fine with the IEC 61850 data model generated by the other module "datamodelgenerator", where
        all LN, DO and DA are linked with a template instead of being specified explicitly.
    - Since a uncertain number of cdc types are not yet supported by libiec61850 (e.g. CSG, CUG, VSG, ORG), they will
        be removed in the dictionary _scl_model, which is a deepcopy of the original scl. This removal affects
        both the data attributes in the model structure (i.e. LN Templates), as well as associated DataSets and
        ReportControlBLocks, DO/DA/Enum templates remain untouched, because additional template at those levels
        won't cause error during the general integrity check on the client side.
    - Besides, some other DA/BDAs are not yet supported in libiec61850, in those cases, a None type will be returned as 
        da_obj after calling the method da_obj = iec61850.ModelNode_getChild(iec61850.toModelNode(do_obj), da_entry['@name'])
        however, the code will not log any message and those DA will not be dumped, which may cause a model inconsistency
        on the server side.
    - Using other communication protocol such as MQTT can possibly bypass the cdc type support issue.

Hints for debugging:
    - always be careful with LLN0, as it allows no prefix and instance. This makes LLN0 an exemption when handling
        Logical Node properties. I tried to implement logics to catch those exemptions, but one can never be 100% sure,
        if error occurs, LLN0 might be the cause, remember that!
    - through out the whole module I used variable name dictXX (e.g. ld_model, dictLN, dictDO...) to refer to the
        associated dictionary object in the SCL data model, I tried to make sure that those var names will not interfere
        with each other in different method calls, but this could still cause error under a certain circumstance.

Known unsupported cdc types:
    - CUG: Currency setting group
    - CSG: Curve shape setting
    - ORS: Object reference status
    - ORG: Object reference setting
    - TCS: Time value status
    - TSG: Time setting group
    - VSG: Visible string setting

TODO: there are a bunch of supporting methods that do not rely on the IEC61850ServerMMS object, consider move them
    outside the object and convert them into normal functions
    

libiec61850 controlOptions according to official doc:
    Link: https://support.mz-automation.de/doc/libiec61850/c/latest/group__COMMON__DATA__CLASSES.html
    #define 	CDC_CTL_MODEL_NONE   0
    #define 	CDC_CTL_MODEL_DIRECT_NORMAL   1
    #define 	CDC_CTL_MODEL_SBO_NORMAL   2
    #define 	CDC_CTL_MODEL_DIRECT_ENHANCED   3
    #define 	CDC_CTL_MODEL_SBO_ENHANCED   4
    #define 	CDC_CTL_MODEL_HAS_CANCEL   (1 << 4)
    #define 	CDC_CTL_MODEL_IS_TIME_ACTIVATED   (1 << 5)
    #define 	CDC_CTL_OPTION_ORIGIN   (1 << 6)
    #define 	CDC_CTL_OPTION_CTL_NUM   (1 << 7)
    #define 	CDC_CTL_OPTION_ST_SELD   (1 << 8)
    #define 	CDC_CTL_OPTION_OP_RCVD   (1 << 9)
    #define 	CDC_CTL_OPTION_OP_OK   (1 << 10)
    #define 	CDC_CTL_OPTION_T_OP_OK   (1 << 11)
    #define 	CDC_CTL_OPTION_SBO_TIMEOUT   (1 << 12)
    #define 	CDC_CTL_OPTION_SBO_CLASS   (1 << 13)
    #define 	CDC_CTL_OPTION_OPER_TIMEOUT   (1 << 14)
"""

# standard python modules
import sys
import os
import xmltodict
import copy
from collections import OrderedDict
import time
import random
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Type, TypedDict
import uuid
import json
import pandas as pd

import numpy as np
import logging
import threading

# standard lib requiring installation


# local python modules
from settings import config, helper
from settings.helper import rotating_logger
from settings.config import Container, IedConfig, DER
from interface.data_buffer import DataBuffer
from interface.iec61850_da import IEC61850DA
from interface.iec61850_do import IEC61850DO
from communication.iec61850_dynamic_model_builder import DataModel


# libs for type hint
from pandas import DataFrame


logger = logging.getLogger(f"main_logger.{__name__}")

iec61850 = helper.import_libiec61850()



@dataclass
class ServerConfig(object):
    """
    An inner-class that stores possible configuration information, either as hard coded variable/constant,
    or extracted from a JSON config file.
    """
    
    TIME_OFFSET: float = 0.0
    # ban the usage of several special characters as they are standard separators in IEC 61850
    INVALID_CHARS: tuple = ('_', '@', '$')
    is_force_destroy: bool = False
    container:Container|None = None
    der: DER|None = None

@dataclass
class IedServer(object):
    """
    An inner-class to store the IED server object as well as status information.
    Key performance indicators should be regularly exchanged with the parameters in the IED server.
    """

    # TODO: check if the structure is too complex, sometimes we need ied_server.ied_server._swig_obj in other modules
    _swig_obj: Type["SwigPyObject"] | None = None  # ignore warning regarding the data type
    
    # TODO: use dict instead of list
    # add some properties to track and record the reference of LD/LN objects
    # init dict / set to store the iec61850 LD/LN object references and unique indices
    ld_objs: dict = field(default_factory=dict)
    ln_objs: dict = field(default_factory=dict)
    ld_obj_ids: set = field(default_factory=set)
    ln_obj_ids: set = field(default_factory=set)
    current_ld_obj_id: int = 0
    current_ln_obj_id: int = 0
    current_ld_obj: Type["SwigPyObject"] | None = None
    current_ln_obj: Type["SwigPyObject"] | None = None
    current_ld_name: str | None = None
    current_ln_name: str | None = None
    data_buffers: dict = field(default_factory=dict)

    version: str = '1.0'

    @property
    def swig_obj(self) -> Type["SwigPyObject"]:
        """The getter: returns the internal data model."""
        return self._swig_obj

    @swig_obj.setter
    def swig_obj(self, value: Type["SwigPyObject"]):
        """The setter: allows replacing the entire model with validation."""
        # FIXME: big issue with type hint for swig objects, need to bypass parametric generics Type["SwigPyObject"]
        # if not isinstance(value, Type["SwigPyObject"]):
        #     raise TypeError("data_model must be a dictionary.")
        self._swig_obj = value

@dataclass
class Statistic(object):
    """
    An inner-class that keep tracking some important records of the running server.
    Key performance indicators should be regularly exchanged with the parameters in the IED server.
    
    The instance of this class requires interaction with local storage, otherwise the records will be lost
    after a restart.
    """
    ld_count: int = 0
    da_count: int = 0
    ds_count: int = 0
    rcb_count: int = 0
    data_model_mod_count: int = 0
    server_restart_count: int = 0

@dataclass
class IEC61850ServerMMS(object):
    """
    The main body of a runtime IEC 61850 server that is initialised using an IEC 61850
    data model (the SCL file).
    """

    def __init__(self, path_scl_import: str, path_lookup:str=None, **kwargs):
        """
        Initialization of a virtual IEC 61850 MMS server.
        since inner-classes with a bunch of properties could give us an insight into the information processing,
        we currently stay with this unpythonic way of class initialization.

        NOTE: one may consider a more efficient way of handling data buffers
            Regarding the attribute data_buffers, usually we would use standard data
            interface to transmit data between python environment and the running IED server,
            this is done by the class DataBuffer, you may consider it a "global variable".
            
            Currently, the class IEC61850ServerMMS owns an attribute data_buffers, which is based on
            the MMS address of each single DA as id. Each time when a control value comes from
            the watch dog, it takes him nlogn time complexity to find where the value should be written.
            Besides, the representation in a list of over 1000 parameters may not be the best for the
            user, so we may have to find a way out.

            As the size of data model grows, this could be critical. Here are some alternatives:
                - store some key information in a pandas DataFrame
                - use the shadow of the IEC 61850 server object (with its tree structure) for DA search
                - split the list into hierachical dictionaries and search by LD -> LN -> DO -> DA -> SDA
        
        """

        self.id_map: dict = {}
        self.lock = threading.Lock()
        self.path_scl_import = path_scl_import  # path of the IEC 61850 data model, or in other words the SCL file
        self.path_scl_export = (f'./model/outputs/{datetime.now().strftime("%Y-%m-%dT%H%M%S")}_mod_'
                                f'{os.path.basename(path_scl_import)}')

        # TODO: add assertion to ensure that path are correct

        if 'path_config_json' in kwargs:
            # TODO: update this section later to include flexible configuration (e.g. IP, port etc.)
            self.path_config_json = kwargs['path_config_json']
        else:
            self.path_config_json = None
        
        # TODO: check whether some of the tasks can be taken over by other sub-modules after the code reconstruction.
        self._data_model: DataModel = DataModel()
        self._ied_server = IedServer()
        self._data_buffers: dict = {}

        self.server_config: ServerConfig = ServerConfig()
        config_template = config.IedConfig()
        self.server_config.container = config_template.container
        self.statistic: Statistic = Statistic()

        # TODO: the variable name ref means a python reference of the object. Consider using a more appropriate name?
        # TODO: convert the lists below into one dataframe

        self.do_mms_addrs: list = []
        self.monitor_objs: list = []
        self.monitor_obj_addrs: list = []
        self.control_objs: list = []
        self.control_obj_addrs: list = []
        self.da_mms_addrs: list = []
        self.quality_objs: list = []
        self.time_objs: list = []
        self.data_buffer_count: int = 0
        self.df_lookup: DataFrame | None = None
        self.df_lookup_active: DataFrame | None = None
        self.container_guid: str | None = None
        self.container_name: str | None = None

        # direct read SCL data model during initialisation
        is_success = self._data_model.parse_scl_data_model(self.path_scl_import)
        assert is_success, 'Parsing SCL data model returned error, please check the file path and SCL contents.'

        self.path_lookup = f'./settings/IEC61850_DA_lookup_{self._data_model.ied_name}.csv' if not path_lookup else (
            path_lookup)

    def add_data_buffer(self, data_buffer):
        # This works because 'self.data_buffers' is now a real dict
        self.data_buffers.update({data_buffer.index: data_buffer})

    @property
    def data_model(self) -> DataModel:
        """The getter: returns the internal data model."""
        return self._data_model

    @data_model.setter
    def data_model(self, value: DataModel):
        if not isinstance(value, DataModel):
            raise TypeError("data_model must be a dictionary.")
        self._data_model = value

    @property
    def ied_server(self) -> IedServer:
        """The getter: returns the internal data model."""
        return self._ied_server

    @ied_server.setter
    def ied_server(self, value: IedServer):
        if not isinstance(value, IedServer):
            raise TypeError("ied_server must be a dictionary.")
        self._ied_server = value


    @property
    def data_buffers(self) -> dict:
        """The getter: returns the internal data model."""
        return self._data_buffers

    @data_buffers.setter
    def data_buffers(self, value: dict):
        if not isinstance(value, dict):
            raise TypeError("data_buffers must be a dictionary.")
        self._data_buffers = value

    def __repr__(self):
        """ The debugging string representation of the MMS server object """
        pass

    def __str__(self):
        """ The readable string representation of the MMS server """
        pass

    def topo_validator(self):
        """
        TODO: implementation in demand
        This method validates the topology of the SCL file and returns info in case the validation failed.
        The topology validator checks:
            - if all LD, LN have unique name (id)
            - if the DataSets and Reports are properly connected
            - ... ...
        """

        pass

    def build_ied_data_model(self):
        """
        Build the IED data model according to the topology of the input SCL file.
        """

        logger.info('Start the build process of a new IEC 61850 data model.')
        if self.data_model.swig_obj is not None:
            # TODO: consider how to preserve the data model reversion
            logger.warning('There exists already a data model, the build process will overwrite it.')
            self.data_model.archives.append(self.data_model.swig_obj)

        self.data_model.swig_obj = iec61850.IedModel_create(self.data_model.ied_name)
        logger.info(f'Date model with the IED name {self.data_model.ied_name} has been generated')

        # Now iteratively build LD
        ld_models = self.data_model.server_model_orig['LDevice']
        if type(ld_models) is not list:
            ld_models = [ld_models]
        for i, ld in enumerate(ld_models):
            self.ied_server.current_ln_obj_id = 0
            # NOTE: currently only modified ld_model is saved, it is assumed that no interim information is helpful.
            ld_model = self.build_ld_obj(ld)
            ld_model = self.add_ds_to_ld(ld_model)
            ld_model = self.add_rcb_to_ld(ld_model)

            if len(ld_models) == 1:
                self.data_model.server_model['LDevice'] = ld_model
            else:
                self.data_model.server_model['LDevice'][i] = ld_model
                self.ied_server.current_ld_obj_id += 1
        logger.info('Data model build process finished')
        return self.data_model

    def build_ld_obj(self, ld_model:dict) -> dict:
        """
        This method builds an object that contains the child objects of one Logical Device.
        Before creating the LD objects, the data model object must have been initialized and stored
        in self._swig_obj.

        In the SCL file, the one-liner LN/DO/DA looks like this:
        <LN desc="Default MMXU template" inst="1" lnType="MMXU_0" lnClass="MMXU" prefix=""></LN>
        <DO desc="" type="MV_0" name="TotW"></DO>
        <DA bType="Struct" fc="MX" name="mag" dchg="true" dupd="true" type="AnalogueValue_0"></DA>
        <EnumVal ord="1">Single phase to neutral</EnumVal>

        TODO: modularise this function!
        NOTE:
            - the LD name shall not contain the special character '_', if so, it will automatically be removed
            - only the dict ld_model_mod will be modified analogously and returned
            - LLN0 must be handled differently as other LN
        """

        ld_model_mod = copy.deepcopy(ld_model)
        # dump not allowed special characters in LD name and create the LD object
        ld_name_orig = ld_model['@inst']
        logger.info(f'Checking LD name of {ld_name_orig}')
        ld_name = self.dump_invalid_char('LD', ld_name_orig)
        ld_model_mod['@inst'] = ld_name
        self.ied_server.current_ld_name = ld_name

        logger.info(f'Create Logical Device {ld_name} in the IED server')
        ld_obj: Type['SwigPyObject'] = iec61850.LogicalDevice_create(ld_name, self.data_model.swig_obj)
        self.ied_server.ld_obj_ids.add(self.ied_server.current_ld_obj_id)
        self.ied_server.ld_objs.update({self.ied_server.current_ld_obj_id:ld_obj})
        self.ied_server.current_ld_obj = ld_obj

        # start building the Logical Node
        logger.info(f'Start the build process for the LD {ld_name}')

        # first build LLN0
        if 'LN0' not in ld_model:
            logger.warning('Logical Node LLN0 not found, the builder moves forward, please check the data model later')
        else:
            ld_model_mod['LN0']['@lnClass'] = self.dump_invalid_char('LN0', ld_model['LN0']['@lnClass'])
            ln0_name = self.get_ln_name(ld_model['LN0'])
            self.ied_server.current_ln_name = ln0_name
            ln0_type = ld_model['LN0']['@lnType']
            ln0_obj: Type['SwigPyObject'] = iec61850.LogicalNode_create(ln0_name, ld_obj)

            # record the iec61850 object references
            self.ied_server.current_ln_obj = ln0_obj
            # use the pair (ld_obj_id, ln_obj_id) as key of the ln_obj in the dict
            current_ln_id_pair = (self.ied_server.current_ld_obj_id, -1,)
            self.ied_server.ln_obj_ids.add(current_ln_id_pair)
            self.ied_server.ln_objs.update({current_ln_id_pair: ln0_obj})

            # Now dump unsupported DO in the LN templates
            index = next((i for i, ln in enumerate(self.data_model.ln_templates)
                          if ln['@id'] == ln0_type), None)
            if index is not None:
                self.data_model.ln_templates_buffer[index] = self.build_do_in_ln(ln0_obj, self.data_model.ln_templates[index])
            else:
                logging.error(f"LN type {ln0_type} not found in templates.")

        # then build all other LNs
        ln_models = ld_model['LN']
        if type(ln_models) is not list:
            ln_models = [ln_models]
        
        for i, ln_model in enumerate(ln_models):
            ld_model_mod['LN'][i]['@lnClass'] = self.dump_invalid_char('LN', ln_model['@lnClass'])
            ln_name = self.get_ln_name(ln_model)
            self.ied_server.current_ln_name = ln_name
            ln_type = ln_model['@lnType']
            ln_obj: Type['SwigPyObject'] = iec61850.LogicalNode_create(ln_name, ld_obj)

            # record the iec61850 object references
            self.ied_server.current_ln_obj = ln_obj
            # use the pair (ld_obj_id, ln_obj_id) as key of the ln_obj in the dict
            current_ln_id_pair = (self.ied_server.current_ld_obj_id, self.ied_server.current_ln_obj_id,)
            self.ied_server.ln_obj_ids.add(current_ln_id_pair)
            self.ied_server.ln_objs.update({current_ln_id_pair:ln_obj})
            self.ied_server.current_ln_obj_id += 1

            # Now dump unsupported DO in the LN templates
            index = next((i for i, ln in enumerate(self.data_model.ln_templates)
                          if ln['@id'] == ln_type), None)
            if index is not None:
                self.data_model.ln_templates_buffer[index] = self.build_do_in_ln(ln_obj, self.data_model.ln_templates[index])
            else:
                logging.error(f"LN type {ln_type} not found in templates.")

        return ld_model_mod
    
    
    def create_data_buffer(self, do_obj:Type["SwigPyObject"], do_entry:dict, sdo_entry: dict|None=None) -> DataBuffer:
        """
        This method automatically create a DataBuffer instance and add it to the attribute data_buffers.
        But the initially created instace contains only limited amount of information, many attributes require 
        update later after server initialization, e.g. first get config info / mapping table / lookup table and
        then update the attributes in the DataBuffer accordingly.
        
        To perform the tasks correctly, the call of this method must be placed in the middel of the method 
        self.build_do_in_ln.
        
        Since DO/SDO is the key of the DataBuffer instances, and the configuration of DO/SDO in the libiec61850 
        IED server is based on DO/SDO type templates, this method requires passing the associated
        refObject and entry to specify DO/SDO, DA and SDO related information.
        
        SDO objects have been considiered during the implementation, this was mainly due to the application of DEL and WYE
        for three phase systems.
        
        Inputs:
            - do_obj: the reference object of the associated DO (DA can not be accessed through SDO!)
            - do_entry: entry of the DO in the dictTemplateDO
            - sdo_entry: entry of the SDO in the dictTemplateDO, leave it None to represent the non-existence of SDO objects
        """
        
        data_buffer = DataBuffer()
        
        # first set its own attributes
        data_buffer.index = self.data_buffer_count
        self.data_buffer_count += 1
        data_buffer.data_source = 'disabled'  # default is disabled, to avoid unnecessary data volume
        
        if sdo_entry is not None:
            data_buffer.iec61850_do.level = 'SDO'
            mms_addr = f'{self.data_model.ied_name}_{self.ied_server.current_ld_name}/{self.ied_server.current_ln_name}.{do_entry["@name"]}.{sdo_entry["@name"]}'
            comm_addr = f'{self.data_model.ied_name}${self.ied_server.current_ld_name}${self.ied_server.current_ln_name}${do_entry["@name"]}${sdo_entry["@name"]}'
            data_buffer.iec61850_do.name = f'{do_entry["@name"]}.{sdo_entry["@name"]}'
            data_buffer.iec61850_do.type = sdo_entry['@type']
            data_buffer.iec61850_do.cdc = sdo_entry['@type'].split('_')[0]
        else:
            mms_addr = f'{self.data_model.ied_name}_{self.ied_server.current_ld_name}/{self.ied_server.current_ln_name}.{do_entry["@name"]}'
            comm_addr = f'{self.data_model.ied_name}${self.ied_server.current_ld_name}${self.ied_server.current_ln_name}${do_entry["@name"]}'
            data_buffer.iec61850_do.name = do_entry['@name']
            data_buffer.iec61850_do.type = do_entry['@type']
            data_buffer.iec61850_do.cdc = do_entry['@type'].split('_')[0]
        
        data_buffer.id = mms_addr  # currently use the IEC 61850 MMS address as id

        # This is only the guid data_buffer, the guid of container will be passed by other methods as data_buffer.container_guid
        # NOTE: if a lookup table exists, then the guid will be later updated from there!
        data_buffer.guid = str(uuid.uuid4())
        
        # IEC 61850 DO
        data_buffer.iec61850_do.id = mms_addr
        data_buffer.iec61850_do.mms_addr = mms_addr
        data_buffer.iec61850_do.comm_addr = comm_addr

        # FIXME: major refactoring once for all
        data_buffer.iec61850_do.obj_ref_map['ld'] = self.ied_server.current_ld_obj
        data_buffer.iec61850_do.obj_ref_map['ln'] = self.ied_server.current_ln_obj
        data_buffer.iec61850_do.obj_ref_map['do'] = do_obj
        
        self.add_data_buffer(data_buffer)
        
        return data_buffer

    @staticmethod
    def add_da_to_data_buffer(data_buffer_do: DataBuffer, da_entry:dict, da_obj: Type["SwigPyObject"],
                              bda_name:str|None=None) -> IEC61850DA:
        """
        This method can be used to create a instance of interface.runtime.IEC61850DA.
        It requires the initialization of a DataBuffer that contains DO information, this method only initialize
        DA instances for the data buffer and add them to the list.
        It should be called during the iterative creation of DA in the method self.build_do_in_ln.
        
        NOTE: currently we skip the level SDO, if a DO containing SDO is detected, the function in
                communication._swig_obj will search for the DA in those SDA and add them to the
                _da_objs
        NOTE: this method does not depend on self, but for now it is better to let it stay here.
        """
        
        iec61850_da = IEC61850DA()
        iec61850_da.level = 'DA'
        
        # first create the IEC61850DA instance
        mms_addr = f'{data_buffer_do.iec61850_do.mms_addr}.{da_entry["@name"]}'
        comm_addr = f'{data_buffer_do.iec61850_do.comm_addr}${da_entry["@name"]}'
        iec61850_da.name = da_entry['@name']

        
        if bda_name is not None:
            mms_addr = f'{mms_addr}.{bda_name}'
            comm_addr = f'{mms_addr}${bda_name}'
            iec61850_da.name = f'{iec61850_da.name}.{bda_name}'
            iec61850_da.level = 'BDA'
        
        iec61850_da.id = mms_addr
        iec61850_da.mms_addr = mms_addr
        iec61850_da.comm_addr = comm_addr
        iec61850_da.do_mms_addr = data_buffer_do.iec61850_do.mms_addr
        iec61850_da.do_comm_addr = data_buffer_do.iec61850_do.comm_addr
        if '@type' in da_entry:
            iec61850_da.type = da_entry['@type']
        iec61850_da.bType = da_entry['@bType']
        iec61850_da.fc = da_entry['@fc']
        iec61850_da.guid = str(uuid.uuid4())

        assert isinstance(data_buffer_do.iec61850_do.obj_ref_map, dict)
        iec61850_da.ld_obj_ref = data_buffer_do.iec61850_do.obj_ref_map['ld']
        iec61850_da.ln_obj_ref = data_buffer_do.iec61850_do.obj_ref_map['ln']
        iec61850_da.do_obj_ref = data_buffer_do.iec61850_do.obj_ref_map['do']
        iec61850_da.da_obj_ref = da_obj
        
        data_buffer_do.iec61850_do.add_iec61850_da(iec61850_da)
        
        return iec61850_da
        
    
    def update_data_buffer(self, data_buffer:DataBuffer, do_obj:Type['SwigPyObject'], da_models:list,
                           sdo_entry:dict|None=None):
        """
        This method can be used to update the properties of newly created data_buffer instances.
        The update of information is based on the _da_objs of associated DO.
        
        Attention: the created data_buffer could be a DO or SDO, make sure you are aware of the information level of
        associated object when this method is called.
        
        Input:
            - data_buffer: the DataBuffer instance to be updated
            - do_obj: the reference of the DO object in the libiec61850 server
            - _da_objs: usally extracted in the dictTemplateDO or dictTemplateSDO
        """
        
        # TODO: pack the DO.SDO.DA.BDA logic as a method
        for da_entry in da_models:
            # NOTE: all BDA will be added to the _da_objs, one could check whether this is necessary
            if da_entry['@bType']=='Struct' and '@type' in da_entry:  # True if da_entry has BDA
                bda_model = [da_type for da_type in self.data_model.da_templates
                                   if da_type['@id'] == da_entry['@type']]
                if not bda_model:
                    logger.info(f'Can not find the DA template dictionary for BDA type {da_entry["@type"]}')
                    logger.info('Search for DA can not proceed, skip this BDA, not data buffer will be created.')
                else:
                    bda_model = bda_model[0]
                    if type(bda_model['BDA']) is not list:
                        bda_models = [bda_model['BDA']]
                    else:
                        bda_models = bda_model['BDA']
                        
                for bda_entry in bda_models:
                    bda_name = bda_entry["@name"]
                    # I'm too lazy to search deeper in this hierachy, so just assume BDA with bType
                    #    Struct and name mag will point to mag.f
                    if bda_name == 'mag':
                        bda_name = 'mag.f'
                    
                    if sdo_entry is not None:
                        bda_id_str = f'{sdo_entry["@name"]}.{da_entry["@name"]}.{bda_name}'
                    else:
                        bda_id_str = f'{da_entry["@name"]}.{bda_name}'
                    bda_obj = iec61850.ModelNode_getChild(iec61850.toModelNode(do_obj), bda_id_str)
                    iec61850_bda = self.add_da_to_data_buffer(data_buffer, da_entry, bda_obj, bda_name)
            else:
                if sdo_entry is not None:
                    da_id_str = f'{sdo_entry["@name"]}.{da_entry["@name"]}'
                else:
                    da_id_str = da_entry["@name"]
                da_obj = iec61850.ModelNode_getChild(iec61850.toModelNode(do_obj), da_id_str)
                iec61850_da = self.add_da_to_data_buffer(data_buffer, da_entry, da_obj, None)
    
    def add_data_buffer_info(self, data_buffer: DataBuffer):
        """
        Use this method to add the created data_buffer instance and its properties to the lists.

        """
        # TODO: refactory here once for all
        self.do_mms_addrs.append(data_buffer.iec61850_do.mms_addr)
        self.monitor_obj_addrs.append(data_buffer.iec61850_do.obj_ref_map['monitor_da_mms_addr'])
        self.control_obj_addrs.append(data_buffer.iec61850_do.obj_ref_map['control_da_mms_addr'])
        self.monitor_objs.append(data_buffer.iec61850_do.obj_ref_map['monitor_da'])
        self.control_objs.append(data_buffer.iec61850_do.obj_ref_map['control_da'])
        self.quality_objs.append(data_buffer.iec61850_do.obj_ref_map['monitor_da_q'])
        self.time_objs.append(data_buffer.iec61850_do.obj_ref_map['monitor_da_t'])

        # if data_buffer.DO.da_mms_addrs is not None:
        #     self.da_mms_addrs += data_buffer.DO.da_mms_addrs
            
    def build_do_in_ln(self, ln_obj: Type['SwigPyObject'], ln_template:dict):
        """
        This method build the entire DO object based on the contents in the DO template dictionary. The current LN
        object in iec61850._swig_obj must be passed as an input argument to the parameter ln_obj.
        During the DO build process, unsupported DA will be removed in the _server_model object, this is done by
        returning the objectLNBuilt object and passing to self.data_model._server_model after calling it.
        """

        ln_model_mod = copy.deepcopy(ln_template)  # this dictionary will be modified analogously and returned
        do_dumps = []
        logger.info(f'Start build Data Objects in LN {ln_template["@id"]}, DO of unsupported cdc type will be dropped, '
                    'dropping a DO may cause data model inconsistency, please validate the data model afterwards!')
        for i, do_entry in enumerate(ln_template['DO']):
            # the DO type is always 2 or 3 char before the _ in @type
            func_handler_name = f'CDC_{do_entry["@type"].split("_")[0]}_create'
            if not hasattr(iec61850, func_handler_name):
                # logger.warning('cdc type {} not supported by libiec61850, dropping DO {} of type {} '
                #                'from LN Template {}'.format(typeDO, do_entry['@name'], do_entry['@type'], ln_template['@id']))
                do_dumps.append(i)
            else:
                func_handler = getattr(iec61850, func_handler_name)
                # TODO: when creating DO in LN, some cdc types (e.g. ASG, APC) have more than 3 parameters, check
                #  whether any exemption is required for those
                
                if func_handler_name[4:7] == 'ASG':
                    do_obj = func_handler(do_entry['@name'], iec61850.toModelNode(ln_obj), 0, False)
                elif func_handler_name[4:6] == 'MV':
                    do_obj = func_handler(do_entry['@name'], iec61850.toModelNode(ln_obj), 0, False)
                elif func_handler_name[4:7] == 'APC':
                    do_obj = func_handler(do_entry['@name'], iec61850.toModelNode(ln_obj), 0, 2, False)
                elif func_handler_name[6] == 'C':
                    do_obj = func_handler(do_entry['@name'], iec61850.toModelNode(ln_obj), 0, 1)
                else:
                    do_obj = func_handler(do_entry['@name'], iec61850.toModelNode(ln_obj), 0)

                # Now iteratively add the DA and SDA to the DO object
                do_template = [do_type for do_type in self.data_model.do_templates
                                  if do_type['@id'] == do_entry['@type']]

                if not do_template:
                    logger.info('Can not find the DO template dictionary, probaly manually created data model.')
                    logger.info('Search for DA can not proceed, skip this DO, not data buffer will be created.')
                else:
                    # first check if SDO exists
                    sdo_models = self.get_items_from_dict(do_template[0], 'SDO')
                    if sdo_models:
                        for sdo_entry in sdo_models:
                            # attention, returned objectSDO is not of type sDataObject, but sModelNode, so objectSDO will never be used.
                            sdo_obj = iec61850.ModelNode_getChild(iec61850.toModelNode(do_obj), sdo_entry['@name'])
                            sdo_template = [do_type for do_type in self.data_model.do_templates
                                               if do_type['@id'] == sdo_entry['@type']]
                            if not sdo_template:
                                logger.info('Can not find the DA template dictionary, probaly manually created data model.')
                                logger.info('Search for SDA can not proceed, skip this SDO, not data buffer will be created.')
                            else:
                                # add a DataBuffer instance for each SDO
                                # Attention! Only the DO objects have SDO children, DA can only be accessed through DO objects, not SDO!
                                data_buffer = self.create_data_buffer(do_obj, do_entry, sdo_entry)
                                da_models = self.get_items_from_dict(sdo_template[0], 'DA')
                                self.update_data_buffer(data_buffer, do_obj, da_models, sdo_entry)
                                
                                data_buffer.iec61850_do.select_primary_da()
                                self.add_data_buffer_info(data_buffer)
                    else:            
                        # add a DataBuffer instance for this DO
                        data_buffer = self.create_data_buffer(do_obj, do_entry)
                        da_models = self.get_items_from_dict(do_template[0], 'DA')
                        self.update_data_buffer(data_buffer, do_obj, da_models)
    
                        data_buffer.iec61850_do.select_primary_da()
                        self.add_data_buffer_info(data_buffer)

        if do_dumps:
            logger.warning(f'Drop {len(do_dumps)} DO from the LN Template {ln_template["@id"]}')
            while do_dumps:
                idx = do_dumps.pop()
                logger.warning('Dropping DO {} of type {} from LN template {}.'.format(ln_template['DO'][idx]['@name'],
                                                                                       ln_template['DO'][idx]['@type'],
                                                                                       ln_template['@id']))
                del ln_model_mod['DO'][idx]  # dump the unsupported DO reversely

        return ln_model_mod

    def add_ds_to_ld(self, ld_model:dict):
        """
        This method takes the dictionary of one LD (ld_model) as input, extract the Data Sets contained in the
        Logical Nodes and add them to self.data_model._swig_obj.

        Because the DataSet in one LN can include DO from other LNs under the same parent LD, so the execution of this
        method must be performed after the entire LD build process has been finished. In other words, the function call
        should not be place within the method 'build_ld_obj', but rather in 'build_ied_data_model' after
        build_ld_obj has been called.

        It follows this approach:
            1. iteration over all DS in all LN in the LD
            2. for each of the fcda (functionally constrained data attribute) in every DS, localise the associated
                LN that has the same lnClass, lnInst and prefix by combining them in a tuple
            3. get the lnType of that DS, then find the associated LN template in self.data_model.ln_templates_buffer.
            4. check whether the fcda name is still in the DO list of that LN template
            5. If the DO is in the list, create the DataSet fcda entry, otherwise dump it from the DS

        Note:
             - the Data Sets could contain DO of unsupported cdc type, here they should also be removed from the
                data model.
             - an important assumption is that the DS of one certain LD will not include parameters in other LDs
        """

        if not self.data_model.ln_templates_buffer:
            raise ValueError('The LN Templates have not been validated by the method build_do_in_ln()!')

        ld_model_mod = copy.deepcopy(ld_model)

        # Step 1: iterate all DataSets in all LN in the LD
        ln_models = copy.deepcopy(ld_model['LN'])
        ln_models.append(ld_model['LN0'])
        # create a list of all LN identifiers in the LD
        ln_identifiers = [self.get_ln_id('LD', v) for i, v in enumerate(ln_models)]

        for i, ln_model in enumerate(ln_models):
            _ln_name = self.get_ln_name(ln_model)
            log_msg = f'The LN {_ln_name} has no DataSet'
            ds_models = self.get_items_from_dict(ln_model, 'DataSet', log_msg, 'info')
            if i == len(ln_models)-1:  # the last element implies LLN0, which should have the index -1
                _ln_idx = -1
                is_lln0 = True
            else:
                _ln_idx = i
                is_lln0 = False

            # get parent LN object that owns the data set
            target_key = (self.ied_server.current_ld_obj_id, _ln_idx)
            parent_ln_obj = self.ied_server.ln_objs.get(target_key)

            if not parent_ln_obj:
                # Handle the case where the LN doesn't exist
                logger.error(f"LN with ID {target_key} not found.")
                logger.error(f"The resulting data model may have inconsistency regarding data set {target_key}.")

            ds_dumps = []  # prepare a list for to be dumped dataSets (empty DataSets)
            for j, ds_model in enumerate(ds_models):
                ds_name = ds_model['@name']
                log_msg = f'The DataSet {ds_name} has no fcda element, check the data model again!'
                fcda_models = self.get_items_from_dict(ds_model, 'FCDA', log_msg, 'warning')

                # Step 2.1: for each fcda in each DS, get the id of target LN
                fcda_dumps = []
                for k, fcda_model in enumerate(fcda_models):
                    fcda_name = fcda_model['@doName']
                    parent_ln_id_str = self.get_ln_id('DS', fcda_model)
                    # Step 2.2: localise the associated LN by indexing the id
                    parent_ln_id_idx = [idx for idx, val in enumerate(ln_identifiers) if val == parent_ln_id_str]
                    # Step 3: determine the LNType of associated LN using the id index
                    if not parent_ln_id_idx:
                        logger.error(f'Identifier search implies no match, there is something wrong with the '
                                     f'data model, double check if the entry {fcda_name} in DataSet {ds_name} '
                                     f'is valid')
                        logger.warning(f'One DataSet entry {fcda_name} in {parent_ln_id_str} can not be created, '
                                       f'double check the data model. Incorrect DataSet entry may result data model '
                                       f'inconsistency on the client side!')
                        continue
                    elif parent_ln_id_idx[0]==len(ln_identifiers)-1:  # this implies the associated LN is LLN0
                        parent_ln_type = ld_model['LN0']['@lnType']
                    else:
                        parent_ln_type = ld_model['LN'][parent_ln_id_idx[0]]['@lnType']
                    # Step 4: check if the DO is still contained in the LN Template
                    # since the LN template has unique id, we expect either an empty list or a list with one element
                    valid_ln_types = [(idx,val) for idx,val in
                                    enumerate(self.data_model.ln_templates_buffer) if val['@id'] == parent_ln_type]
                    if not valid_ln_types:
                        logger.error(f'The target LN template {parent_ln_type} not found, double check the data model!')
                    else:
                        (parent_ln_idx, parent_ln_models) = valid_ln_types[0]

                        # Step 5.1: add the DataSet fcda entry to dump list
                        valid_do_names = [do_entry['@name'] for do_entry in parent_ln_models['DO']]
                        if fcda_name not in valid_do_names:
                            logger.info(f'Can not find DO {fcda_name} in the LN Template after build, dump fcda in DS')
                            fcda_dumps.append(k)

                # Step 5.2: dump the DataSet fcda entry
                if len(fcda_dumps) == len(fcda_models):  # this implies all fcda must be dumped -> del the DS
                    ds_dumps.append(j)
                    continue
                elif not fcda_dumps:
                    #pass
                    #listDictFCDAUpdated = dictLDBuiltUpdated['LN'][idxLNInLD]['DataSet'][idxDSInLN]['fcda']
                    fcda_models_mod = copy.deepcopy(fcda_models)  # nothing to dump, move forward
                else:
                    # listDictFCDAUpdated = listDictFCDA
                    if is_lln0:
                        while fcda_dumps != []:
                            fcda_dump_idx = fcda_dumps.pop()
                            fcda_dump_name = ld_model_mod['LN0']['DataSet'][j]['FCDA'][fcda_dump_idx]['@doName']
                            logger.warning(f'fcda with reference {fcda_dump_name} is dumped in the DataSet {ds_name}.')
                            del ld_model_mod['LN0']['DataSet'][j]['FCDA'][fcda_dump_idx]
                        fcda_models_mod = copy.deepcopy(ld_model_mod['LN0']['DataSet'][j]['FCDA'])
                    else:
                        while fcda_dumps != []:
                            fcda_dump_idx = fcda_dumps.pop()
                            del ld_model_mod['LN'][i]['DataSet'][j]['FCDA'][fcda_dump_idx]  # remove the fcda in the
                            # data model dict
                        fcda_models_mod = copy.deepcopy(ld_model_mod['LN'][i]['DataSet'][j]['fcda'])

                # Now create the DataSet object
                logger.info(f'Create DS object for the DataSet named {ds_name}, {len(fcda_models_mod)} fcda entries in this DS')
                ds_obj = iec61850.DataSet_create(ds_name, parent_ln_obj)  # create DataSet in server data model
                
                # Attention, the LN name is not nameThisLN, but the name of the LN that contains the DO!!
                    # Assume all DS are in the LD that the LN belongs to
                    # official note in libiec61850:
                    #   Note: Be aware that data set entries are not IEC 61850 object reference but MMS variable names that have to contain the LN
                    #   name, the fc and subsequent path elements separated by "$" instead of ".". This is due to efficiency reasons
                    #   to avoid the creation of additional strings. If the variable parameter does not contain a logical device name (separated from the 
                    #   remaining variable name by the "/" character) the logical device where the data set resides is used automatically.
                
                for fcda_model in fcda_models_mod:
                    if fcda_model['@lnClass'] == 'LLN0':
                        ds_entry_str = '{}${}${}'.format(fcda_model['@lnClass'], fcda_model['@fc'], fcda_model['@doName'])
                    else:
                        ds_entry_str = '{}{}{}${}${}'.format(fcda_model['@prefix'], fcda_model['@lnClass'], fcda_model['@lnInst'],
                                                           fcda_model['@fc'], fcda_model['@doName'])
                    
                    fcda_obj = iec61850.DataSetEntry_create(ds_obj, ds_entry_str, -1, None)

            # Now dump empty DataSets
            if ds_dumps:
                logger.warning(f'Inconsistent DS detected, {len(ds_dumps)} DataSet must be dumped in the LN {_ln_name}')
            while ds_dumps != []:
                ds_dump_idx = ds_dumps.pop()
                if is_lln0:
                    ds_dump_name = ld_model_mod['LN0']['DataSet'][ds_dump_idx]['@name']
                    logger.warning(f'DS with reference {ds_dump_name} is dumped.')
                    del ld_model_mod['LN0']['DataSet'][ds_dump_idx]
                else:
                    ds_dump_name = ld_model_mod['LN'][i]['DataSet'][ds_dump_idx]['@name']
                    logger.warning(f'DS with reference {ds_dump_name} is dumped.')
                    del ld_model_mod['LN'][i]['DataSet'][ds_dump_idx]
        return ld_model_mod

    def add_rcb_to_ld(self, ld_models:dict|None=None):
        """
        This method takes the dictionary of one LD (ld_model) as input, extract the Report Control Blocks
        contained in the Logical Nodes and accordingly add them to self.data_model._swig_obj. Normally, the
        reports will be linked to DS that is (are) contained in the same Logical Node, well to make the entire module
        compatible for other IEC 61850 data model, this method will still scan all Logical Nodes in one LD and check
        whether the DS reference is valid.

        TODO: add log messages for this method

        Note:
            - Regarding the report configuration on the server side, this method will not change anything, it just
                takes over the original configuration as they are in the data model.
            - Theoretically, we can always search for the corresponding reports as long as one DataSet has been created,
                well this will require a second-level iteration of RCB search over all LN within the first-level loop,
                which is surely an error source. To avoid problems associated with this, this method is added to the
                module. Basically it triggers another first-level loop search after the DS build process is finished.
            - This method has some duplicate codes in add_ds_to_ld, well I won't make the effort to improve this.
        """

        ld_models_mod = copy.deepcopy(ld_models)

        # Step 1: iterate all DataSets in all LN in the LD
        ln_models = copy.deepcopy(ld_models['LN'])
        ln_models.append(ld_models['LN0'])
        # create a list of all LN identifiers in the LD
        ln_identifiers = [self.get_ln_id('LD', ln_model) for idx, ln_model in enumerate(ln_models)]

        for i, ln_model in enumerate(ln_models):
            _ln_name = self.get_ln_name(ln_model)
            if i == len(ln_models) - 1:  # the last element implies LLN0, which should have the index -1
                _ln_idx = -1
                is_lln0 = True
            else:
                _ln_idx = i
                is_lln0 = False
            target_key = (self.ied_server.current_ld_obj_id, _ln_idx)
            parent_ln_obj = self.ied_server.ln_objs.get(target_key)
            log_str = f'The LN {_ln_name} has no Report Control Block'
            rcb_models = self.get_items_from_dict(ln_model, 'ReportControl', log_str, 'info')
            for j, rcb_model in enumerate(rcb_models):
                # first get basic info
                rcb_name = rcb_model['@name']
                rcb_id = rcb_model['@rptID']
                rcb_ref_ds = rcb_model['@datSet']
                rcb_integrity = int(rcb_model['@intgPd'])
                rcb_conf_rev = int(rcb_model['@confRev'])
                if '@buffered' in rcb_model:
                    is_buffered = rcb_model['@buffered']
                else:
                    is_buffered = False  # if not defined, a report is set to be unbuffered
                if '@bufTime' in rcb_model:
                    buffer_time = int(rcb_model['@bufTime'])  # TODO: add a type check here
                else:
                    buffer_time = 0  # if not defined, buffer time is set to 0

                # calculate bit mask for trigger options
                trigger_opt_models = rcb_model['TrgOps']
                trigger_opts = {'@dchg': 1, '@qchg': 2, '@dupd': 4, '@period': 8, '@gi': 16}
                flag_tri_opt = 0
                for key, val in trigger_opts.items():
                    flag_tri_opt = flag_tri_opt + val*bool(trigger_opt_models.get(key, False))

                # calculate bit mask for option fields
                opt_field_models = rcb_model['OptFields']
                opt_fields = {'@seqNum': 1, '@timeStamp': 2, '@reasonCode': 4, '@dataSet': 8, '@dataRef': 16,
                                '@BufOvfl': 32, '@entryID': 64, '@configRef': 128}
                flag_opt_field = 0
                for key, val in opt_fields.items():
                    flag_opt_field = flag_opt_field + val*bool(opt_field_models.get(key, False))

                # build Report Control Block objects
                rcb_obj = iec61850.ReportControlBlock_create(rcb_name, parent_ln_obj, rcb_id, is_buffered, rcb_ref_ds,
                                                   rcb_conf_rev, flag_tri_opt, flag_opt_field,
                                                   buffer_time, rcb_integrity)

        return ld_models_mod

    def create_ied_server(self) -> Type["SwigPyObject"] | None:
        """ Run the IED Server using the data model built by self.build_ied_data_model. """

        logger.info('Create the IED server using current version of the data model')
        assert self.data_model.swig_obj, 'No data model available, please build the data model first!'

        # NOTE: onc could consider add topology check before running the server.
        # Currently, we assume the data model is okay
        swig_obj = iec61850.IedServer_create(self.data_model.swig_obj)
        logger.info('The IED server has been created')

        self.ied_server.swig_obj = swig_obj
        DataBuffer.ied_server_swig_obj = swig_obj

        logger.info('The IED server swig object has been attached to the DataBuffer class')

        return swig_obj

    def destroy_ied_server(self):
        """Cleanly stop and destroy libiec61850 C objects."""

        swig_obj = getattr(self.ied_server, 'swig_obj', None) if hasattr(self, 'ied_server') else None

        if swig_obj is not None:
            try:
                # 1. Stop TCP server from accepting new connections / stop worker threads
                iec61850.IedServer_stop(swig_obj)

                # 2. Free C memory allocated for the IED server instance
                iec61850.IedServer_destroy(swig_obj)

                logger.info("IEC 61850 C-Server stopped and destroyed cleanly.")
            except Exception as e:
                logger.error(f"Failed to destroy C-Server object: {e}")
            finally:
                # Clear reference so repeated calls or checks evaluate to None
                self.ied_server.swig_obj = None
                DataBuffer.ied_server_swig_obj = None
        else:
            logger.warning("destroy_ied_server called, but no active C-Server object was found.")

    def dump_invalid_char(self, obj_level:str='LD', obj_str:str='dummy'):
        """
        This method helps to dump not allowed characters in the object name, it returns the updated name.
        obj_level could be LD, LN, DO.....
        """
        for i, char in enumerate(self.server_config.INVALID_CHARS):
            if char in obj_str:
                obj_str = obj_str.strip(char)
                logger.warning(f'The {obj_level} name {obj_str} contains banned character'
                               f' {char}, automatically removed')
        return obj_str

    @staticmethod
    def get_items_from_dict(dict_obj:dict, key:str, log_str:str|None=None, log_level:str= 'info') -> list:
        """
        This method checks if an item (which should be a list) with given key exists and returns the list of it.

        If the list contains only a single element of the list, its type will be OrderedDict.

        The third argument could be a log message if the item does not exist, with given log_level. Log level are the
        standard levels of built-in function logging (info, error, warning, ...)
        """

        vals = []
        if key not in dict_obj:
            if log_str is not None:
                log_func = getattr(logger, log_level)
                log_func(log_str)
        elif isinstance(dict_obj[key], dict):  # this implies a single fcda, OrderedDict is also dict
            vals = [dict_obj[key]]
        elif isinstance(dict_obj[key], list):
            vals = dict_obj[key]
        # leave out the else here to catch runtime errors
        return vals

    @staticmethod
    def get_ln_name(ln_model:dict) -> str:
        """ This method takes the dictionary object of a LN and build the LN name string. """
        if ln_model['@lnClass'] == 'LLN0':
            return f'{ln_model["@lnClass"]}{ln_model["@inst"]}' # although the inst should be ''
        else:
            return f'{ln_model["@prefix"]}{ln_model["@lnClass"]}{ln_model["@inst"]}'

    @staticmethod
    def get_ln_id(level:str, ln_model:dict) -> tuple:
        """
        This method creates an id for one Logical Node dictionary taken from the SCL data model, which is either
        a 'fcda' dict from a DataSet, or an element of the 'LN0' or 'LN' list in the dict 'LDevice'. This method will be
        called when searching for the LN that contains the DO in a DataSet.

        Input parameter:
            - level: either 'DS' or 'LD', unknown level will cause returning a tuple with an empty string
            - ln_model: the dict object that contains the id information
        output parameter:
            - identifierLN: the id of the LN
        """

        if level == 'DS':
            if ln_model['@lnClass'] == 'LLN0':  # LLN0 is a exemption, it has no prefix and lnInst
                ln_id = (ln_model['@lnClass'],)
            else:
                ln_id = (ln_model['@lnClass'], ln_model['@lnInst'], ln_model['@prefix'])
        elif level == 'LD':
            if ln_model['@lnClass'] == 'LLN0':  # LLN0 is an exemption, it has no prefix and lnInst
                ln_id = (ln_model['@lnClass'],)
            else:
                ln_id = (ln_model['@lnClass'], ln_model['@inst'], ln_model['@prefix'])
        else:
            ln_id = ('',)

        return ln_id

    @staticmethod
    def get_iec61850_tstmp(tstmp_unix:float):
        """ This method will convert a Unix timestamp (float) into the format that the IEC 61850 compliant
         IED Server can understand, more specifically, it converts the seconds to milliseconds"""

        iec61850_tstmp = None
        SCALE_FACTOR = 1000
        if not isinstance(tstmp_unix, (float, np.float64, np.float32, np.floating)):
            logger.warning('Wrong data type, input timestamp must be a Unix float value')
        else:
            iec61850_tstmp = tstmp_unix * SCALE_FACTOR

        return iec61850_tstmp

    def export_scl_data_model(self):
        """ This function outputs the updated data model after the build process as a SCL file. """

        # first overwrite the modified part in self.data_model._scl_model
        self.data_model.scl_model['SCL']['IED']['AccessPoint']['Server'] = self.data_model.server_model
        self.data_model.scl_model['SCL']['DataTypeTemplates']['LNodeType'] = self.data_model.ln_templates_buffer

        # then export the file
        with open(self.path_scl_export, 'wt', encoding='utf-8') as fo:
            xmltodict.unparse(self.data_model.scl_model, fo, pretty=True)
            logger.info(f'The IEC 61850 data model has been successfully generated in: {self.path_scl_export}')
            
    def create_lookup_table(self):
        """
        This method exports a CSV file that contains the DO and DA addresses and placeholders
        for essential DataBuffer configuration. This file can later be updated by other modules to synchronize 
        configuration information.
        
        The file will always be stored in ./settings with the name IEC61850_DA_lookup_{self.data_model.ied_name}.csv
        
        NOTE: this config file is only a workaround in the prototype, later those information should be stored in a
        local or remote database.
        """
        
        logger.info('Create the lookup table for the running IED')
        df_lookup = pd.DataFrame({
            'index': None,
            'mms_addr': self.do_mms_addrs,
            'monitor_da': self.monitor_obj_addrs,
            'control_da': self.control_obj_addrs,
            'data_source': None,
            'fieldbus_conn_config': None,
            'fieldbus_conn_obj': None,
            'guid': None,
            'is_monitor': None,
            'is_control': None,
            'limits': None,
            'rated_value': None,
            'unit_factor': None,
            'scaling_factor': None,
            'unit': None,
            })

        for idx, data_buffer in self.data_buffers.items():
            for key, val in vars(data_buffer).items():
                if key in df_lookup.columns:
                    df_lookup.at[idx, key] = val

        self.df_lookup = df_lookup


    def read_lookup_csv(self, columns: list|None=None):
        """
        This method can be used to load the lookup table of the running IED (if it exists). After a complete
        scan, values on and only on requested columns will be modified both in the DataBuffer instances and 
        in the df attribute.
        
        If ied_config.interface.forceOverwrite is set to True, the updated DO configuration, i.e. the df
        attribute could be exported using another method exportIedLookupCSV(), which overwrites the existing CSV lookup table.
        
        Attention: DO NOT USE this method without specifying the columns to be read! Before doing this,
        make sure you know what kind of information those columns contain. Reading csv configuration on 
        certain columns (e.g. conn_obj object, or tuple will be load as string) can mess up with data types completely!
        
        Especially when a lookup table already exists, and it is pre-configured along with a ready-to-use
        SCL file. In this case, a user might consider only update a part of the lookup table without destroying a 
        functioning runtime service. 
        
        It is worth mentioning that the lookup table mainly deals with dynamic parameter (analog, interger, enum, etc.),
        which update regularly in real-time application. Static information such as description
        parameters (e.g. DPL, LPL) are listed, but without monitorDA and controlDA.
        
        ====================================================================================================
        
        Well, the possiblity of reading existing configuration could be very useful regarding the generation of 
        guid and other unique identifiers, so keep this method on the development pipelilne.
        
        FIXME: fix the data type problematic when calling pd.read_csv() before putting this method in use. Check
          the data type of each column in the lookup table, implement data type conversion when necessary.
        
        NOTE: the local lookup table can later be replaced by a central meta-info database.
        NOTE: always check the lookup table first before the server initialization, and use existing
            configuration for the data_buffer.

        TODO: this function is overnested, need to resolve it into smaller function blocks

        TODO: it is super strange to put functions for updating data_buffer here, use methods of DataBuffer!
        """
        
        path =  self.path_lookup
        if not os.path.exists(path):
            logger.warning('The lookup table does not exist, no read action will be performed.')
        elif columns is None:
            logger.warning('No column names is specified, can not proceed to the reading CSV action.')
        else:
            df_lookup = pd.read_csv(path, engine='python')
            if len(df_lookup) == 0:
                logger.warning('The lookup talbe is empty, no read action will be performed.')
            elif not any(x in df_lookup for x in self.df_lookup):
                logger.warning('No item in the column name list matches the lookup table of running service, no read action will be performed.')
            else:
                valid_cols = [x for x in df_lookup if x in self.df_lookup]
                logger.info('Update the instances of DataBuffer and self.df.')
                logger.info(f'List of column names: {columns}')
                logger.info(f'List of configured data_sources: {set(df_lookup["data_source"])}')
                server_mms_addrs = self.df_lookup['mms_addr'].to_list()
                lookup_mms_addrs = df_lookup['mms_addr'].to_list()
               
                # during the read process, we create a new databuffer list with only those in the lookup table,
                # this could avoid index mismatching.
                # TODO: find a better way to solve the index mismatch problem caused by different software versions.
                data_buffers_mod = {}
                mms_addr_dumps = []
                
                for idx, dbf in self.data_buffers.items():
                    if dbf.iec61850_do.mms_addr in lookup_mms_addrs:
                        idx_server = server_mms_addrs.index(dbf.iec61850_do.mms_addr)
                        idx_lookup = lookup_mms_addrs.index(dbf.iec61850_do.mms_addr)
                        for key in df_lookup.keys():
                            if key in dbf.__dict__.keys():
                                value = df_lookup.loc[idx_lookup, key]
                                # extract specific configuration from the fieldbus_conn_config column
                                # TODO: there will be more and more special handlings, need a function handler here
                                if key == 'fieldbus_conn_config':
                                    config = helper.safe_parse_config(value)
                                    dbf.fieldbus_conn_config = config

                                    if v := config.pop('value', None): dbf.value_external = v
                                    if p := config.pop('provider', None): dbf.local_timeseries.provider = p

                                    # # # TODO: does influxdb require the same handling?
                                    # if 'time_col' in config_json.keys():
                                    #     data_buffer.time_col = config_json.get('time_col', None)
                                    # if 'data_col' in config_json.keys():
                                    #     data_buffer.data_col = config_json.get('data_col', None)
                                    #
                                    # for key, val in config_json.items():
                                    #     if not hasattr(data_buffer, key):
                                    #         setattr(data_buffer, key, val)
                                    dbf.update_attribute_kwargs(**config)


                                elif key == 'limits':
                                    '''
                                    Here we add a special handling for limits
                                    Very important notion regarding the application of (upper or lower) limits
                                     - default is a dict dict({'lower': -999999999, 'upper': 999999999}) given by interface.runtime.DataBuffer()
                                     - many control values or simulated measurements are restricted by those boundaries 
                                     - limits are checked by the method processing.routine.update_external_value() 
                                     - so, always update limits before writing a value to the IEC 61850 server.
                                     # FIXME: what if limits is not a str?
                                    '''
                                    if isinstance(value, str):
                                        limits = json.loads(value.replace("\'", "\""))
                                        # if type(dictLimit['lower']) in [int, np.int, np.int8, np.int32]:
                                        dbf.limits[0] =  limits['lower']
                                        dbf.limits[1] =  limits['upper']
                                    elif isinstance(value, dict):
                                        dbf.limits[0] = value['lower']
                                        dbf.limits[1] = value['upper']
                                    else:
                                        raise ValueError('Unknown value types for limits')

                                elif value is None:
                                    # better use default setting if not specified, nan / None would cause much more problems.
                                    pass
                                else:
                                    setattr(dbf, key, value)
                                    self.df_lookup.loc[idx_server, key] = value
                        data_buffers_mod.update({dbf.index: dbf})
                        self.df_lookup.loc[idx, 'isConsistent'] = 1
                    else:
                        mms_addr_dumps.append(dbf.iec61850_do.mms_addr)
                        self.df_lookup.loc[idx, 'isConsistent'] = 0
                
                # TODO: check is it necessary to dump inconsistent dataBuffers and rows in the lookup table?
                if mms_addr_dumps:
                    logger.info('Detected lookup table inconsistency, drop following DO in the databuffer list')
                    logger.info(f'{mms_addr_dumps}')
                    self.data_buffers = data_buffers_mod
                    # listDropIndex = self.df.loc[self.df['isConsistent'] == 0].index
                    # self.df.drop(index=listDropIndex, inplace=True)
                else:
                    logger.info('The lookup table is consistent with the auto-generated one, no action required.')
            
                                                                     

    def get_active_do_in_lookup(self):
        """
        This method creates a dataframe of all active (monitor or control) DOs, which
        helps to narrow down the search area of run time data processing.

        TODO: consider also using data_source to determine if DO is active

        Returns
        -------

        """

        # 1. Vectorized boolean mask for active rows
        is_active = (self.df_lookup['is_monitor'] == True) | (self.df_lookup['is_control'] == True)

        # 2. Filter original dataframe directly
        df_lookup_active = self.df_lookup[is_active].copy()

        # 3. Preserve original row index as 'idxBuffer' column
        df_lookup_active.reset_index(names='idxBuffer', inplace=True)

        self.df_lookup_active = df_lookup_active

        # Logging counts
        num_monitor = (self.df_lookup['is_monitor'] == True).sum()
        num_control = (self.df_lookup['is_control'] == True).sum()
        logger.info(
            f'Created lookup table of {len(df_lookup_active)} active DO '
            f'({num_monitor} monitor DO, {num_control} control DO).'
        )
        logger.info(f'Created lookup table of {len(df_lookup_active)} active DO, {num_monitor} monitor DO and {num_control} control DO')


    def export_lookup_csv(self):
        """
        This method can be used to export the updated lookup table of the running IED.
        Be careful when calling this function, it uses DataBuffer instances to overwrite lookup configuration.
        
        DO NOT call this method when you are in the middle of processing the lookup table!!

        TODO: too many duplicated codes here, do a code merge later.
        """
        
        path =  self.path_lookup
        
        if not os.path.exists(path):
            logger.warning('The lookup table does not exist.')
        elif len(self.df_lookup) == 0:
            logger.warning('The lookup talbe is empty, no export necessary.')
        else:
            # # catch the updates in data_buffer objects and change the lookup table accordingly
            # for idx, data_buffer in enumerate(self.data_buffers):
            #     for key, val in data_buffer.__dict__.items():
            #         if key in self.df_lookup.keys():
            #             if type(val) is dict:
            #                 val = str(val)
            #             self.df_lookup.loc[idx, key] = val
            # self.df_lookup.to_csv(path)

            # Convert the list of data_buffer dicts directly into a DataFrame
            new_data = pd.DataFrame([vars(b) for b in self.data_buffers.values()], index=self.data_buffers.keys())

            # Stringify any dictionary columns before saving
            for col in new_data.select_dtypes(include=['object']):
                new_data[col] = new_data[col].apply(lambda x: str(x) if isinstance(x, dict) else x)

            # Update the lookup and export_compose_file
            self.df_lookup.update(new_data)
            self.df_lookup.to_csv(path)
            logger.info('Successfully exported the lookup table of running IED by accessing data buffer instances')
            
        
        
    def create_guid_table(self):
        """
        This method should export a csv file containing the newly created guid of DO, DA and other associated stuff,
        this list can be used to recap the guid when re-initializing the service with identical configuration.
        
        TODO: instead of just overwrite, make a copy of that CSV file and put it in './dump' first?

        NOTE: in the future the local storage should be replaced by a central guid (meta-info) database. Well the
           basic structure of the dataFrame can be preserved.

        TODO: column names have been changed in the guid table, also change those in other scripts that take data in
        the guid table as inputs.
        """
        
        logger.info('Create the guid list for the running IED')
        rows = []

        for _, data_buffer_do in self.data_buffers.items():
            # extract DO-level info
            do_obj = data_buffer_do.iec61850_do
            do_info = {
                'index': data_buffer_do.index,
                'guid': data_buffer_do.guid,
                'do_name': do_obj.name,
                'do_identifier': do_obj.id,
                'do_guid': do_obj.guid,
            }

            # extract DA instances and build rows
            for da in do_obj.get_da_instances():
                rows.append({
                    **do_info,  # Merges DO-level info into this dictionary
                    'da_name': da.name,
                    'da_identifier': da.id,
                    'da_guid': da.guid,
                })

        df_guid = pd.DataFrame(rows)
        df_guid.to_csv(f'./settings/IEC61850_da_guid_{self.data_model.ied_name}.csv')
        logger.info('Successfully finished the export of guid list for the running IED')

    def create_data_buffer_map(self):
        """ generate a id map for efficient id search"""
        self.id_map = {item.iec61850_do.id: idx for idx, item in self.data_buffers.items()}

def data_model_mod_tracker():
    """
    This is a placeholder for the function that keeps tracking the data model reversion and detecting modification.
    """

    pass



def run_ied_server_mms(ied_config: IedConfig, disp_interval:float=None):
    """
    This function builds and starts the IEC 61850 MMS server.
    """
        
    iec61850_server_mms = IEC61850ServerMMS(ied_config.interface.path_scl, ied_config.interface.path_lookup)

    data_model = iec61850_server_mms.build_ied_data_model()
    iec61850_server_mms.export_scl_data_model()
    ied_server = iec61850_server_mms.create_ied_server()
    iec61850_server_mms.create_lookup_table()
    iec61850_server_mms.create_data_buffer_map()
    
    iec61850_server_mms.container_guid = ied_config.container.container_guid
    iec61850_server_mms.container_name = ied_config.container.container_name
    
    # export lookup table as a CSV file
    logger.info(f'Path for lookup CSV: {iec61850_server_mms.path_lookup}')
    if os.path.isfile(iec61850_server_mms.path_lookup):
        if ied_config.interface.is_force_overwrite:
            logger.info('Found existing lookup table with the same filename, just overwrite it for security reasons.')
            iec61850_server_mms.export_lookup_csv()
        else:
            # NOTE: not force overwriting the lookup table may cause data inconsistence, only for test purpose.
            # TODO: -> add a function, updateLookupCSV() (as readLookCSV is not working properly)
            # one only needs to iterate by mms_addr and update guid and other stuff.
            iec61850_server_mms.read_lookup_csv(ied_config.interface.read_lookup_columns)
            logger.info('Found existing lookup table with the same filename, do not overwrite.')
    
    else:
        logger.info('Lookup table does not exist, create it.')
        iec61850_server_mms.export_lookup_csv()

    iec61850_server_mms.get_active_do_in_lookup()
    
    # TODO: is it necessary to check existing guid list to avoid overwriting?
    iec61850_server_mms.create_guid_table()
    
    logger.info('Pass the container_guid also to each data_buffer')
    for i, data_buffer in iec61850_server_mms.data_buffers.items():
        data_buffer.container_guid = iec61850_server_mms.container_guid
        data_buffer.container_name = iec61850_server_mms.container_name
    
    iec61850.IedServer_start(iec61850_server_mms.ied_server.swig_obj, ied_config.ied.tcp_port)
    logger.info('The IED server has been started')

    return iec61850_server_mms


